# Generated by Django 3.1.5 on 2021-03-25 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driverPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.IntegerField()),
                ('daystart', models.DateTimeField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('drat', 'Drat'), ('published', 'Published')], default=' published', max_length=50)),
            ],
        ),
    ]
