# Generated by Django 3.1.5 on 2021-05-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preworktour', '0002_driverpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpost',
            name='slug',
            field=models.SlugField(max_length=225, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='driverpost',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
