# Generated by Django 3.1.5 on 2021-05-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusers',
            name='image_account',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
